### ISSUE TITLE
Can you provide a Spring Boot + Kotlin sample?

### ISSUE THREAD

**Issue by patrick-at-ifood** [jjohannes/gradle-project-setup-howto#19]
I am trying to setup it by myself and keep getting the `The Kotlin Gradle plugin was loaded multiple times` message.

**Comment by jjohannes** [comment]
Hi @patrick-at-ifood. To understand this error one hast to understand that Gradle can load a different sets of plugins for each (sub)project. However, some plugins – like the _Kotlin Gradle plugin_ – cannot deal with this and give such errors. To avoid this, we have to "force" Gradle to load the same plugins for all (sub)projects.

The current setup of this project may cause this, because the plugins are split up into multiple "plugin projects". From each of this projects, a Jar is created (containing all the plugins of the corresponding project). The Jars are only loaded by a project, if a plugin from the Jars is used (a lot of Gradle magic).

_current structure_
```
└── gradle
    └── plugins
        ├── base-plugins
        ├── build.gradle.kts
        ├── dependency-analysis-plugins
        ├── dependency-rules-plugins
        ├── java-application-plugins
        ├── java-base-plugins
        └── java-library-plugins
```

I plan to change the setup of this project, to only have one plugins project. Issues like this and my own experience in multiple projects showed, to me, that this splitup has mostly disadvantages. (Note: we discussed this topic [here](https://github.com/jjohannes/gradle-project-setup-howto/issues/10#issuecomment-1354593179).)


_new structure_
```
└── gradle
    └── plugins
        └── build.gradle.kts <-- only one "build.gradle.kts" for all plugins!
```

All external plugins should then be in the dependencies block of that one `build.gradle.kts`.

```
dependencies {
    implementation("com.autonomousapps:dependency-analysis-gradle-plugin:1.30.0")
    implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.21")
    implementation("org.springframework.boot:spring-boot-gradle-plugin:2.7.18")
}
```

Would that change be possible in you case and does it solve the issue for you?

**Comment by patrick-at-ifood** [comment]
I believe that might work just fine, looks to me that it even makes things easier.
Right now I can spend much time on it but I'll return when it's done.

**Comment by jjohannes** [comment]
:+1: It's still work in progress, but I have started work on updating this project and have a branch that follows the setup I was talking about: https://github.com/jjohannes/gradle-project-setup-howto/tree/next_iteration/

**Comment by jjohannes** [comment]
The new setup is now on `main` and the Readme has been updated.

With this structure, I combined the `kotlin` and `spring_boot` branch, and it seems to work fine:
https://github.com/jjohannes/gradle-project-setup-howto/tree/kotlin%2Bspring_boot
