### ISSUE TITLE
Question: Spring Boot dependency management plugin

### ISSUE THREAD

**Issue by randyhbh** [jjohannes/gradle-project-setup-howto#20]
Hi @jjohannes, Thank you for all the effort you have put into this repo and for sharing your knowledge about Gradle through your fantastic compilation of videos on YouTube.

I was reviewing the setup project for Java + Spring Boot that you have shared, and I noticed that the `id("io.spring.dependency-management") version "1.1.4"` plugin, which provides dependency version resolution for all Spring Boot based projects, was not used.

I am curious to know why you chose not to use this plugin. I would appreciate it if you could share your thoughts on this matter.

**Comment by jjohannes** [comment]
Hi @randyhbh. Thanks for the feedback and the question. 🙏 

I think the docs on the `id("io.spring.dependency-management")` are not very clear on this topic. Since Gradle 6, Gradle fully supports using BOMs directly. Which in most cases makes the plugin obsolete. In special cases it may have some interesting additional functionality. I found [this issue comment](https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/211#issuecomment-387362326) listing the differences.

I prefer not using the plugin if not specifically needed, because it _may_ have unexpected effects on the resolution result by the way it "forces" all versions of _spring-boot-dependencies_. But it can be a choice to use the plugin if there is a good reason.

In this example, I do not use it and have [this](https://github.com/jjohannes/gradle-project-setup-howto/blob/spring-boot/gradle/platform/build.gradle.kts#L14) instead in the [platform project](https://docs.gradle.org/current/userguide/java_platform_plugin.html#sec:java_platform_bom_import):

```
dependencies {
  api(platform("org.springframework.boot:spring-boot-dependencies:2.7.18"))
  // ...
}
```

Which means that my own platform/BOM extends the _spring-boot-dependencies_ platform/BOM.
