### ISSUE TITLE
Kotlin Gradle plugin loaded multiple times

### ISSUE THREAD

**Issue by phreed** [jjohannes/gradle-project-setup-howto#7]
When running gradle on this project I get the following message:
```text
The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build.
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':application-plugins', ':base-plugins'
```

This sounds bad.
Is it bad?

**Comment by jjohannes** [comment]
Thanks for reporting. Seems like this does not break anything, but it is annoying. 

Short explanation: It's due to plugin classloading weirdness cause by one of the _gradle/plugins_ subprojects adding an additional plugin (_org.gradlex.build-parameters_) on top of _kotlin-dsl_ while the other projects there don't do that. This leads to different plugin classpathes in different subprojects which the Kotlin Gradle Plugin (wokring underneath _kotlin-dsl_) does not like. 

```
plugins {
    `kotlin-dsl`
    id("org.gradlex.build-parameters") version "1.0"
}
``` 

vs.

```
plugins {
    `kotlin-dsl`
}
```

**Comment by jjohannes** [comment]
Defined the build parameters in a separate subproject now, which solves this:
https://github.com/jjohannes/gradle-project-setup-howto/blob/main/gradle/settings-plugins/build-parameters/build.gradle.kts

Also moved it to be part of the "settings" plugins so that we can use it to read the "CI" env variable in one of the settings plugins:
https://github.com/jjohannes/gradle-project-setup-howto/blob/main/gradle/settings-plugins/settings/src/main/kotlin/org.example.gradle-enterprise.settings.gradle.kts#L12
